### ISSUE TITLE
"Screen Sharing Unavailable" on ZorinOS

### ISSUE THREAD

**Issue by NelloKudo** [maltejur/discord-screenaudio#11]
I tried compiling the app from source on Zorin OS 16.1 (debian based) and everything seemed fine but when I launch the app and try screensharing, Discord says it's not available and redirects me to its official package.
Here's a video example: https://streamable.com/r9jmfo

I'll also upload logs, hopefully they show something xd

[logs.txt](https://github.com/maltejur/discord-screenaudio/files/9190381/logs.txt)

**Comment by maltejur** [comment]
It looks like something is wrong with the injected userscript. I'll try to reproduce it if I have time

**Comment by maltejur** [comment]
Ok I can reproduce the issue

![image](https://user-images.githubusercontent.com/48161361/181270756-db55020b-3ec2-466e-98a5-e77c3f33abf9.png)

**Comment by maltejur** [comment]
The core of this problem is that Zorin is based on Ubuntu 20, which is quite outdated. The version of QtWebEngine used here is 5.12.8, which uses Chromium 69. And in that version of Chromium, Discord just doesn't seem to be able to stream video, even in the browser: 

![Screenshot_20220727_204137](https://user-images.githubusercontent.com/48161361/181348354-54984935-e977-458e-b4a2-a9354a3caa92.png)

So your best shot is probably to get a newer version of Qt from some ppa.

**Comment by maltejur** [comment]
I've been trying to create a AppImage or Flatpak to solve this issue, but I haven't had success with that so far.

**Comment by NelloKudo** [comment]
I’ll wait for the appimage/flatpak then, in the meanwhile I’ll try with some PPAs and let you know more 🥳

Ty for your work <3

**Comment by maltejur** [comment]
If you want you can already try [this](https://shorsh.de/upload/d20a/discord-screenaudio-v1.0.0-rc.7-x86_64.AppImage) appimage, but for me it isn't working.

**Comment by NelloKudo** [comment]
The appimage actually launches properly but gives off this: 

`[discord] "Uncaught (in promise) NotReadableError: Could not start video source"`

Hopefully it's gonna work soon e.e

**Comment by NelloKudo** [comment]
I don't know if this might help, but I got a sort of "fix":
I added this ppa through:

```
sudo add-apt-repository ppa:beineri/opt-qt-5.15.0-focal
sudo apt update
source /opt/qt515/bin/qt515-env.sh
```

and now the app launches the stream correctly, but the dialog asking for the app or screen to show isn't working.
I guess that is probably due to some bug in that QtWebEngine version, but interesting enough xD

example: https://streamable.com/l5ezrt

I still think either an Appimage/Flatpak/Snap would be the best option, hopefully I'll try to look more into those myself e.e

**Comment by maltejur** [comment]
Hm, interesting. When I use the ppa you linked, the dialog successfully opens for me. But then I have another issue. Once I try to start the stream, Discord becomes unresponsive and some sort of memory leak happens:

https://user-images.githubusercontent.com/48161361/181505403-69d60e71-c450-40f2-a131-853e59144dc2.mp4

This could be because I am inside of a VM. But I still don't know why the dialog didn't show for you, I didn't see any errors in your logs.

**Comment by maltejur** [comment]
Oh I know what it is, you have to set your client to English for now (https://github.com/maltejur/discord-screenaudio/issues/10)

**Comment by NelloKudo** [comment]
The screenshot launches here but shows both monitors and yeah, same memory leak as well xD
I guess the only fix would be an appimage or flatpak, not our fault old libraries ain't doing their job haha

**Comment by NelloKudo** [comment]
Just installed your flatpak and now works flawlessly, the only thing I needed to switch was the streaming's audio to virtmic in pavucontrol. Ty for your work! <3

**Comment by maltejur** [comment]
Ah you already saw :D

I was still working on the flatpak so here is the newest version with all the .desktop stuff working: https://github.com/maltejur/discord-screenaudio/releases/download/v1.0.0-rc.11/discord-screenaudio-v1.0.0-rc.11.flatpak
