### ISSUE TITLE
Discord Noise Suppression by krisp

### ISSUE THREAD

**Issue by kevin0xf** [maltejur/discord-screenaudio#137]
The official discord client recently allows using the noise suppression by krisp that appears next to the disconnect button.
This client apparently does not support it yet, when is the client gonna be updated?

**Comment by kevin0xf** [comment]
I just realized that the noise supression by krisp is not shown on the official discord website, just on the client.
Since this custom client is based on the web view, it does not seem to be possible to implement.

Is there a workaround?

**Comment by D3SOX** [comment]
You can use RNNoise.
I use https://github.com/werman/noise-suppression-for-voice via PipeWire input filter chains.
See this tutorial https://scribe.rip/@gamunu/linux-noise-cancellation-b9f997f6764d on how to set it up.
Otherwise you can try some UI for it like https://github.com/noisetorch/NoiseTorch

**Comment by Taza53** [comment]
I don't know how, but it's working now.
![image](https://github.com/maltejur/discord-screenaudio/assets/34032665/2459edc5-9df1-4d31-9dd1-ef437f88fdbd)
