### ISSUE TITLE
Whats the point?

### ISSUE THREAD

**Issue by Santahgeo** [maltejur/discord-screenaudio#21]
Whats the point of this app if discord already supports audio, screen sharing, and voice chat in its original apps on Xorg. I know it still doesn't support screen sharing on Wayland but this app doesnt either. So whats the true point of this app and what makes it different from discord.

**Comment by NelloKudo** [comment]
I guess you've never tried streaming a movie then 😂

None of Discord's official packages support screensharing with audio, it's a client limitation due to the electron version they use (and they won't probably ever change) and since there are clearly no devs open to work on it xd

Check [this](https://support.discord.com/hc/en-us/community/posts/360050971374-Linux-Screen-Share-Sound-Support?page=2) out
