### ISSUE TITLE
merge discord-screenaudio with vesktop?

### ISSUE THREAD

**Issue by TheRsKing** [maltejur/discord-screenaudio#238]
They are both wonderful projects that pursue exactly the same goal. Wouldn't it be wiser if the workers simply got together and set up an even better project? So we have a single project with the advantages of Vesktop and discord-screenaudio

**Comment by Curve** [comment]
This already exists and is used in Vesktop: https://github.com/Vencord/venmic

**Comment by TheRsKing** [comment]
To be honest, I cannot think of anything at the moment. However, it would be beneficial if you could collaborate. Having two similar projects does not make sense when you could work more efficiently on a single project together. As an outsider, I have no say in the matter. Perhaps you could reach out to Vesktop and inquire about working together. This is only a well-intentioned suggestion, of course.

**Comment by Curve** [comment]
> To be honest, I cannot think of anything at the moment. However, it would be beneficial if you could collaborate. Having two similar projects does not make sense when you could work more efficiently on a single project together. As an outsider, I have no say in the matter. Perhaps you could reach out to Vesktop and inquire about working together. This is only a well-intentioned suggestion, of course.

I am working together with Vesktop :)

This project is based on my library [rohrkabel](https://github.com/Curve/rohrkabel)  on which venmic is based as well, however venmic is currently using the latest rohrkabel version 5.1 (at the time of writing) while this project uses 1.2 I think.

We're always happy to see contributions in either vesktop or venmic, if someone is up for collaboration :)

**Comment by TheRsKing** [comment]
Okay thanks!

**Comment by maltejur** [comment]
discord-screenaudio has a lot of problems stemming from the fact that is uses QtWebEngine instead of Electron. Mainly it has no (or bad) hardware acceleration, resulting in really bad performance on low end systems. But it also only allows you to share your primary screen on X11 (although that will change in a future Qt version). In addition to that, the code isn't in the best state right now and I also have very little time to work on fixing issues that pop up.

So I would be open to adding a kind of "deprecation notice" to discord-screenaudio, telling users that they are probably better off using Vesktop. That would also allow me to possibly contribute to Venmic and Vesktop (if there even is anything still left to improve :) ). What do you think about that @Curve?

**Comment by Curve** [comment]
> So I would be open to adding a kind of "deprecation notice" to discord-screenaudio, telling users that they are probably better off using Vesktop. 

Sounds good! 

I think concentrating the effort into one project is a good idea, especially since we can then battle test the implementation even more to ensure that everyone has the best experience possible :)

I've also begun to work on pulseaudio support for venmic, albeit with lower priority since that implementation will probably need to be thoroughly tested before we ship it since pulse can be a pain to work with sometimes, especially due to some of the default modules which can sadly mess with the whole process a lot (i.e. unwanted audio redirection, ...)

> That would also allow me to possibly contribute to Venmic and Vesktop (if there even is anything still left to improve :) ). What do you think about that @Curve?

We actually have a lot of things still waiting to be implemented in Vesktop and are always grateful for new ideas regarding venmic and or vesktop :)  

Regarding things to improve or theorize upon/about: I've thought about implementing some sort of DSL for venmic to allow for even greater freedom when it comes to how you want the audio to be redirected (this would require some brain-storming before actually realizing this though, as it should be as pleasant as possible for people downstream and I'm not even sure if this might even be out of scope) as well as enabling one to create multiple venmic instances (which would also require some special thought when it comes to pulseaudio support) - I'd love to get feedback on some of the ideas and to [start a discussion](https://github.com/Vencord/venmic/issues) regarding how things should be approached here ^^
