### ISSUE TITLE
[request] provide AppImage in releases

### ISSUE THREAD

**Issue by Lolzen** [maltejur/discord-screenaudio#45]
As the title states.

**Comment by maltejur** [comment]
I already tried to do this (the code is still on the [appimage](https://github.com/maltejur/discord-screenaudio/tree/appimage) branch), but the whole process of creating an appimage was just super scuffed because of wrong system library versions. In the end I even got a .AppImage file, but something with libpipewire didn't work and I just switched to Flatpaks then (which work much better and feel much more polished btw).
