### ISSUE TITLE
Flatpak app not running on artix 

### ISSUE THREAD

**Issue by Mambert** [maltejur/discord-screenaudio#56]
Running `flatpak run de.shorsh.discord-screenaudio` in a terminal returns: 

`QApplication: invalid style override 'gtk2' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion`

`[default] QLayout: Attempting to add QLayout "" to StreamDialog "", which already has a layout`

I attempted to change my GTK/Plasma version through KDE settings, but to no avail.

**Comment by turbo-cunnos** [comment]
Same problem on Ubuntu

**Comment by maltejur** [comment]
I can not reproduce this in a Ubuntu VM. Can you share how to reproduce this?

**Comment by Mambert** [comment]
> I can not reproduce this in a Ubuntu VM. Can you share how to reproduce this?

Running the above command in a terminal of your choice on artix linux, the following errors return, and the program does not start. As described in original comment. 

I believe that Artix is using some sort of custom theming, and it is creating an error. This is given I have no programming knowledge, and still very little linux knowledge. 

I haven't used Ubuntu in a while, I do not know if they use style overrides as well.

**Comment by maltejur** [comment]
I can reproduce the issue, but the problem doesn't seem to be the theming. I can fix the theming message by just running `sudo flatpak override --env=QT_STYLE_OVERRIDE="Breeze" de.shorsh.discord-screenaudio`, but the program still doesn't start.

The problem is that you aren't using pipewire. I think the default on Artix is Pulseaudio. If I use pipewire the problem is fixed for me.
