### ISSUE TITLE
Background run

### ISSUE THREAD

**Issue by federicotorrielli** [maltejur/discord-screenaudio#58]
The app currently does not run in the background, and when closing it just closes.
I think it should mimic discord: when the X is pressed, it goes in the background and the call stays active.
A titlebar icon should be added too, in this case.

**Comment by maltejur** [comment]
As you can read in the readme, I see this application more as a additional client to the standard discord client, to use when you need to stream audio. For that purpose, I like it much more when the application just closes when you press X.

But since some people seem to use this as their main Discord client, I still think this is a valid feature request that could maybe be implemented behind a toggle in the settings.

**Comment by maltejur** [comment]
Relevant implementation guide https://amin-ahmadi.com/2019/06/20/implementing-minimize-to-tray-functionality-using-qt-c/

**Comment by AverageDood** [comment]
I second this one. Discord-screenaudio is already highly usable as a primary Discord client, on par with the available Flatpak, and even better than the official release, as I've encountered stuttering on that last one

**Comment by D3SOX** [comment]
Now, a <kbd>CTRL</kbd> + <kbd>Q</kbd> shortcut inside the application would be nice to exit it.
